services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  nodered:
    image: nodered/node-red:latest
    depends_on:
      - mosquitto
    environment:
      - FLOWS=flows.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data

  simulator:
    build:
      context: ./simulator
    depends_on:
      - mosquitto
    environment:
      - MQTT_URL=mqtt://host.docker.internal:1883
      - ENVIRONMENT=living-room
      - DEVICE_ID=sensor-001
      - MQTT_TOPIC=home/living-room/sensor-001/telemetry
      - MQTT_COMMAND_TOPIC=home/living-room/sensor-001/cmd
      - MQTT_STATUS_TOPIC=home/living-room/sensor-001/status
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["node", "device-simulator.js"]

  simulator_kitchen:
    build:
      context: ./simulator
    depends_on:
      - mosquitto
    environment:
      - MQTT_URL=mqtt://host.docker.internal:1883
      - ENVIRONMENT=kitchen
      - DEVICE_ID=sensor-002
      - MQTT_TOPIC=home/kitchen/sensor-002/telemetry
      - MQTT_COMMAND_TOPIC=home/kitchen/sensor-002/cmd
      - MQTT_STATUS_TOPIC=home/kitchen/sensor-002/status
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["node", "device-simulator.js"]

  simulator_garage:
    build:
      context: ./simulator
    depends_on:
      - mosquitto
    environment:
      - MQTT_URL=mqtt://host.docker.internal:1883
      - ENVIRONMENT=garage
      - DEVICE_ID=sensor-003
      - MQTT_TOPIC=home/garage/sensor-003/telemetry
      - MQTT_COMMAND_TOPIC=home/garage/sensor-003/cmd
      - MQTT_STATUS_TOPIC=home/garage/sensor-003/status
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["node", "device-simulator.js"]

  consumer:
    build:
      context: ./simulator
    depends_on:
      - mosquitto
    environment:
      - MQTT_URL=mqtt://host.docker.internal:1883
      - MQTT_TOPIC=home/#
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["node", "subscriber.js"]
